name: Github Actions workflow for deployment via Terraform

permissions:
  pull-requests: write

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  terraform-check:
    name: Terraform format job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task_1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format
        run: terraform fmt -check

  terraform-plan:
    name: Terraform plan job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task_1
    env:
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_backend_s3_bucket_name: ${{ secrets.BACKEND_S3_BUCKET_NAME }}
      TF_VAR_backend_s3_state_path: ${{ secrets.BACKEND_S3_STATE_PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan

  terraform-apply:
    name: Terraform format job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task_1
    env:
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_backend_s3_bucket_name: ${{ secrets.BACKEND_S3_BUCKET_NAME }}
      TF_VAR_backend_s3_state_path: ${{ secrets.BACKEND_S3_STATE_PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply
