name: Github Actions workflow for deployment via Terraform

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened]

jobs:
  terraform-test:
    name: Terraform test for getting secrets from github
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_backend_s3_bucket_name: ${{ secrets.BACKEND_S3_BUCKET_NAME }}
      TF_VAR_backend_s3_state_path: ${{ secrets.BACKEND_S3_STATE_PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: terraform plan
      - name: Test step for check is GH secrets works in bash
        run: echo "The event type is ${{ github.event.action }}. Vars ${{ TF_VAR_aws_region }}, ${{ TF_VAR_backend_s3_bucket_name }}, ${{ TF_VAR_backend_s3_state_path }}"
      - name: Test step for check is GH secrets works last effort
        run: echo "Vars ${{ secrets.AWS_REGION }}, ${{ secrets.BACKEND_S3_BUCKET_NAME }}, ${{ secrets.BACKEND_S3_STATE_PATH }}"