name: Github Actions workflow for deployment via Terraform

permissions:
  pull-requests: write
  id-token: write
  contents: read


on:
  pull_request:
    branches:
      - master
    types: [opened, reopened]
  push:
    branches:
      - master

jobs:
  terraform-check:
    name: Terraform format job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task_3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format
        run: terraform fmt -check

  terraform-plan:
    needs: terraform-check
    name: Terraform plan job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task_3

    env:
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_backend_s3_bucket_name: ${{ secrets.BACKEND_S3_BUCKET_NAME }}
      TF_VAR_backend_s3_state_path: ${{ secrets.BACKEND_S3_STATE_PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform init
        run: >
          terraform init
          -backend-config="bucket=${{ secrets.BACKEND_S3_BUCKET_NAME }}"
          -backend-config="key=${{ secrets.BACKEND_S3_STATE_PATH }}"
          -backend-config="region=${{ secrets.AWS_REGION }}"
          -backend-config="encrypt=true"

      - name: Terraform plan
        run: terraform plan

  terraform-apply:
    needs: terraform-plan
    name: Terraform apply job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task_3
    env:
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_backend_s3_bucket_name: ${{ secrets.BACKEND_S3_BUCKET_NAME }}
      TF_VAR_backend_s3_state_path: ${{ secrets.BACKEND_S3_STATE_PATH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform init
        run: >
          terraform init
          -backend-config="bucket=${{ secrets.BACKEND_S3_BUCKET_NAME }}"
          -backend-config="key=${{ secrets.BACKEND_S3_STATE_PATH }}"
          -backend-config="region=${{ secrets.AWS_REGION }}"
          -backend-config="encrypt=true"

      - name: Terraform apply
        run: terraform apply -auto-approve
